sudo: required
language: node_js
node_js: stable
services:
    - docker
cache:
  directories:
    - node_modules
install:
    - npm install -g mustache
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"
    - echo "{MAVEN_REGISTRY_PASSWORD: $MAVEN_REGISTRY_PASSWORD}"| mustache - maven_settings.mustache > settings.xml
script:
    - docker build --tag ${DOCKER_REGISTRY}/${REPO_NAME_TAG} ./
    - docker push ${DOCKER_REGISTRY}/${REPO_NAME_TAG} ./
env:
    global:
        - REPO_NAME_TAG: tiggerlee/maven:3.5-jdk-8